[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "djitellopy>=2.5.0",
    "fastapi[standard]>=0.115.12",
    "pycolmap>=3.11.1",
    "rasterio>=1.4.3",
]

[dependency-groups]
dev = [
    "nuitka>=2.6.9",
]

[tool.ruff.lint]
extend-select = ["I", "N", "PL", "UP", "E501", "NPY", "RUF100"]
unfixable = ["F401"]
